[WIP] feat: targets rework with native downloader and unpacker
matter-labs/era-compiler-llvm-builder pull request #25
Opened 2024-04-30 15:18 UTC by antonbaliasnikov

# What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-04-30 18:01 UTC, hedgar2017 requested changes

2024-04-30 18:01 UTC, hedgar2017 commented on src/zkevm_llvm/arguments.rs
> +        use_musl: bool,
Let's make an enum `gnu | musl`?

2024-05-01 12:08 UTC, antonbaliasnikov commented on src/zkevm_llvm/arguments.rs
> +        use_musl: bool,
Done, please, take a look

2024-05-01 13:01 UTC, antonbaliasnikov commented
@hedgar2017 , we need to find a proper way to merge this, because it will require changes in CI in all repos that use builder. 

I suggest to do it as follows:
1. Make sure we release the current `main` to the cargo crate
2. Update other repositories to use LLVM builder from cargo mirror, not from GitHub (as it is now to always take the most recent version)
3. Merge this PR and release a new version to cargo
4. Update other repositories CI with the new version of builder from cargo and update docs at the same time - this will let us to properly test our changes

2024-05-01 13:15 UTC, hedgar2017 commented
> @hedgar2017 , we need to find a proper way to merge this, because it will require changes in CI in all repos that use builder.
> 
> I suggest to do it as follows:
> 
> 1. Make sure we release the current `main` to the cargo crate
> 2. Update other repositories to use LLVM builder from cargo mirror, not from GitHub (as it is now to always take the most recent version)
> 3. Merge this PR and release a new version to cargo
> 4. Update other repositories CI with the new version of builder from cargo and update docs at the same time - this will let us to properly test our changes

Sure! Let's do it now.
Will publish in 5 min.

2024-05-01 13:15 UTC, merged