feat: support of sccache compiler cache variant
matter-labs/era-compiler-llvm-builder pull request #44
Opened 2024-11-20 10:57 UTC by antonbaliasnikov

# What ❔

Add capability to choose compiler cache variation: `ccache` or `sccache`.

## Why ❔

To allow users to use [`sccache`](https://github.com/mozilla/sccache) too as it is more popular and supports Rust too.

## Checklist

- [x] PR title corresponds to the body of PR.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-11-20 16:57 UTC, hedgar2017 requested changes

2024-11-20 16:57 UTC, hedgar2017 commented on src/lib.rs
> +    ccache_variant: ccache_variant::CcacheVariant,
Make these two args `Option<Variant>`?

2024-11-22 11:36 UTC, antonbaliasnikov commented
Added changes into https://github.com/matter-labs/era-compiler-llvm-builder/pull/45 to rebase on top of `clap` with the new arguments.

2024-11-22 11:36 UTC, closed without merging

2024-11-22 14:53 UTC, hedgar2017 commented
@antonbaliasnikov can we remove this branch?